version: "3.9"

services:
  sample-service:
    build:
      context: ./service-sample
      network: host
    image: service-sample:local
    container_name: service-sample-container
    environment:
      FLASK_APP: ${SAMPLE_SERVICE_APP_NAME:-service_sample}
      DEBUG: ${SAMPLE_SERVICE_DEBUG:-True}

      PG_WAREHOUSE_HOST: ${PG_WAREHOUSE_HOST}
      PG_WAREHOUSE_PORT: ${PG_WAREHOUSE_PORT}
      PG_WAREHOUSE_DBNAME: ${PG_WAREHOUSE_DBNAME}
      PG_WAREHOUSE_USER: ${PG_WAREHOUSE_USER}
      PG_WAREHOUSE_PASSWORD: ${PG_WAREHOUSE_PASSWORD}

      TELEGRAM_API_ID: ${TELEGRAM_API_ID}
      TELEGRAM_API_HASH: ${TELEGRAM_API_HASH}

    network_mode: "bridge"
    ports:
      - "5011:5000"
    restart: unless-stopped

  api-service:
    build:
      context: ./api_service
      network: host
    image: hs-api-service:alpha-0.1.5
    container_name: hs-api-service
    environment:
      FLASK_APP: ${SERVICE_APP_NAME:-api_service}

      FLASK_SECRET_KEY: ${FLASK_SECRET_KEY}
      API_ADMIN_KEY: ${API_ADMIN_KEY}

      PG_WAREHOUSE_HOST: ${PG_WAREHOUSE_HOST}
      PG_WAREHOUSE_PORT: ${PG_WAREHOUSE_PORT}
      PG_WAREHOUSE_DBNAME: ${PG_WAREHOUSE_DBNAME}
      PG_WAREHOUSE_USER: ${PG_WAREHOUSE_USER}
      PG_WAREHOUSE_PASSWORD: ${PG_WAREHOUSE_PASSWORD}

      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "5010:5010"
    restart: unless-stopped

  dds-service:
    build:
      context: dds_service
      network: host
    image: hs-dds-service:alpha-0.1.0
    container_name: hs-dds-service
    environment:
      FLASK_APP: ${SERVICE_APP_NAME:-dds_service}

      FLASK_SECRET_KEY: ${FLASK_SECRET_KEY}

      PG_WAREHOUSE_HOST: ${PG_WAREHOUSE_HOST}
      PG_WAREHOUSE_PORT: ${PG_WAREHOUSE_PORT}
      PG_WAREHOUSE_DBNAME: ${PG_WAREHOUSE_DBNAME}
      PG_WAREHOUSE_USER: ${PG_WAREHOUSE_USER}
      PG_WAREHOUSE_PASSWORD: ${PG_WAREHOUSE_PASSWORD}
    ports:
      - "5012:5000"
    restart: unless-stopped

  postgres-db:
    image: postgres:13
    container_name: hs-postgres-db
    environment:
      POSTGRES_DB: ${PG_WAREHOUSE_DBNAME}
      POSTGRES_USER: ${PG_WAREHOUSE_USER}
      POSTGRES_PASSWORD: ${PG_WAREHOUSE_PASSWORD}
    ports:
      - "25432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis/redis-stack-server:latest
    container_name: hs-redis
    environment:
      REDIS_ARGS: ${REDIS_ARGS}
      REDIS_PORT_NUMBER: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_AOF_ENABLED: ${REDIS_AOF_ENABLED}
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 5
    restart: always

  metabase:
    image: metabase/metabase:latest
    container_name: hs-metabase
    depends_on:
      postgres-db:
        condition: service_healthy
    restart: "always"
    ports:
      - "4040:4040"
    environment:
      MB_DB_TYPE: ${MB_DB_TYPE}
      MB_DB_DBNAME: ${MB_DB_DBNAME}
      MB_DB_PORT: ${MB_DB_PORT}
      MB_DB_USER: ${MB_DB_USER}
      MB_DB_PASS: ${MB_DB_PASS}
      MB_DB_HOST: ${MB_DB_HOST}
      MB_JETTY_PORT: ${MB_JETTY_PORT}
