# Set basic image as python 3.10
FROM python:3.10

# Add enviroment arguments
ARG FLASK_SECRET_KEY

# Postgres connection arguments
ARG PG_WAREHOUSE_HOST
ARG PG_WAREHOUSE_PORT
ARG PG_WAREHOUSE_DBNAME
ARG PG_WAREHOUSE_USER
ARG PG_WAREHOUSE_PASSWORD

# Update container components
RUN apt-get update -y

# Copy all files into container
COPY . .

# Setup require packages
RUN pip install -r requirements.txt

# Setup sertificate for cloud connection
# RUN mkdir -p /crt
# RUN wget "https://storage.yandexcloud.net/cloud-certs/CA.pem" --output-document /crt/YandexInternalRootCA.crt
# RUN chmod 0600 /crt/YandexInternalRootCA.crt

# Go to /src directiory
WORKDIR /src

# Set container entrypoint on python enviroment
ENTRYPOINT ["python"]

# Set entrypoint command on app.py
CMD ["app.py"]
